language: ruby
notifications:
  email:
    on_success: never
    on_failure: always
rvm:
 - "2.3.3"
services:
  - postgresql
cache: bundler
env: 
  - RAILS_ENV=development

before_script:
  - sudo apt-get install ruby-dev
  - psql -c 'create database nectar_development;' -U postgres
  - export SECRET_KEY_BASE="$(bundle exec rake secret)"
script: 
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: a3aa46f3d16d10b2fd7566e83a8c9010bd13e96ddf307aec7d69df5cae5756db
#The following two lines are required to compile mini_racer
sudo: required
dist: trusty
