# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  google_provider_key: <%= ENV["GOOGLE_PROVIDER_KEY"] %>
  google_provider_secret: <%= ENV["GOOGLE_PROVIDER_SECRET"] %>
  trello_provider_key: <%= ENV["TRELLO_PROVIDER_KEY"] %>
  trello_provider_secret: <%= ENV["TRELLO_PROVIDER_SECRET"] %>
  quizlet_provider_key: <%= ENV["QUIZLET_PROVIDER_KEY"] %>
  quizlet_provider_secret: <%= ENV["QUIZLET_PROVIDER_SECRET"] %>
  beeminder_provider_key: <%= ENV["BEEMINDER_PROVIDER_KEY"] %>
  beeminder_provider_secret: <%= ENV["BEEMINDER_PROVIDER_SECRET"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  pocket_provider_key: <%= ENV["POCKET_PROVIDER_KEY"] %>
  
  bitbucket_provider_key: <%= ENV["BITBUCKET_PROVIDER_KEY"] %>
  bitbucket_provider_secret: <%= ENV["BITBUCKET_PROVIDER_SECRET"] %>
  dropbox_provider_key: <%= ENV["DROPBOX_PROVIDER_KEY"] %>
  dropbox_provider_secret: <%= ENV["DROPBOX_PROVIDER_SECRET"] %>
  facebook_provider_key: <%= ENV["FACEBOOK_PROVIDER_KEY"] %>
  facebook_provider_secret: <%= ENV["FACEBOOK_PROVIDER_SECRET"] %>
  fitbit_provider_key: <%= ENV["FITBIT_PROVIDER_KEY"] %>
  fitbit_provider_secret: <%= ENV["FITBIT_PROVIDER_SECRET"] %>
  flickr_provider_key: <%= ENV["FLICKR_PROVIDER_KEY"] %>
  flickr_provider_secret: <%= ENV["FLICKR_PROVIDER_SECRET"] %>
  github_provider_key: <%= ENV["GITHUB_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GITHUB_PROVIDER_SECRET"] %>
  instagram_provider_key: <%= ENV["INSTAGRAM_PROVIDER_KEY"] %>
  instagram_provider_secret: <%= ENV["INSTAGRAM_PROVIDER_SECRET"] %>
  khan_academy_provider_key: <%= ENV["KHAN_ACADEMY_PROVIDER_KEY"] %>
  khan_academy_provider_secret: <%= ENV["KHAN_ACADEMY_PROVIDER_SECRET"] %>
  linkedin_provider_key: <%= ENV["LINKEDIN_PROVIDER_KEY"] %>
  linkedin_provider_secret: <%= ENV["LINKEDIN_PROVIDER_SECRET"] %>
  microsoft_office365_provider_key: <%= ENV["MICROSOFT_OFFICE365_PROVIDER_KEY"] %>
  microsoft_office365_provider_secret: <%= ENV["MICROSOFT_OFFICE365_PROVIDER_SECRET"] %>
  moves_provider_key: <%= ENV["MOVES_PROVIDER_KEY"] %>
  moves_provider_secret: <%= ENV["MOVES_PROVIDER_SECRET"] %>
  rtm_provider_key: <%= ENV["RTM_API_KEY"] %>
  rtm_provider_secret: <%= ENV["RTM_SHARED_SECRET"] %>
  runkeeper_provider_key: <%= ENV["RUNKEEPER_PROVIDER_KEY"] %>
  runkeeper_provider_secret: <%= ENV["RUNKEEPER_PROVIDER_SECRET"] %>
  slack_provider_key: <%= ENV["SLACK_PROVIDER_KEY"] %>
  slack_provider_secret: <%= ENV["SLACK_PROVIDER_SECRET"] %>
  strava_provider_key: <%= ENV["STRAVA_PROVIDER_KEY"] %>
  strava_provider_secret: <%= ENV["STRAVA_PROVIDER_SECRET"] %>
  tumblr_provider_key: <%= ENV["TUMBLR_PROVIDER_KEY"] %>
  tumblr_provider_secret: <%= ENV["TUMBLR_PROVIDER_SECRET"] %>
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>
  wunderlist_provider_key: <%= ENV["WUNDERLIST_PROVIDER_KEY"] %>
  wunderlist_provider_secret: <%= ENV["WUNDERLIST_PROVIDER_SECRET"] %>
  
  secret_key_base: <%= ENV["SECRET_KEY_BASE"]  %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  dumper_app_key: <%= ENV['DUMPER_APP_KEY'] %>

test:
  <<: *default

production: &development
  <<: *default
